[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Functions configuration
[functions]
  directory = ".netlify/functions"

# Security: Configure secrets scanning to ignore NEXT_PUBLIC_ variables
# These are intentionally exposed to the client-side and are not secrets
[build.processing]
  skip_processing = false
