# This file is kept for reference only - project now deploys on Vercel
# Netlify configuration (deprecated - use Vercel instead)

# [build]
#   command = "npm run build"
#   publish = ".next"

# [build.environment]
#   NODE_VERSION = "18"
#   NEXT_TELEMETRY_DISABLED = "1"

# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# [functions]
#   directory = ".netlify/functions"
#   node_bundler = "esbuild"

# [build.processing]
#   skip_processing = false

# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "SAMEORIGIN"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"